#spring.application.name=eurekaServerUAT
server.port=9002
eureka.client.register-with-eureka=false
eureka.client.fetchRegistry=false
eureka.client.serviceUrl.defaultZone= http://localhost:9002/eureka/

LOG_FILE_NAME=EurekaServer
LOG_FOLDER_NAME=log
logging.file.path= ${user.dir}
logging.file.name=${LOG_FOLDER_NAME}/${LOG_FILE_NAME}.log
logging.pattern.file= [%d{yyyy-MM-dd' T 'HH:mm:ss.sss' Z'}] [%t] %-5p [%C : %L] - %m%n%throwable
logging.file.max-size = 10MB
logging.level.ROOT = INFO
logging.level.com.netflix.eureka = WARN
logging.file.max-history=180
